### ISSUE TITLE
Directory missing error

### ISSUE THREAD

**Issue by abdulghafor** [herrfeder/AI_Cybersecurity_IDS_PoC#1]
Hi! I have worked as per your instructions. I have succeeded to run the complete code. Unfortunately, I am unable to  run app.
![error1](https://user-images.githubusercontent.com/71027093/105953997-e5feb280-6095-11eb-974f-da3535204624.PNG)
![error2](https://user-images.githubusercontent.com/71027093/105954004-e7c87600-6095-11eb-89ef-2051ca559695.PNG)

**Comment by herrfeder** [comment]
Thank you for sending the issue. Yes we're aware of this and is right now intended as you have to mount your own directory with the zeek logs (conn.log, dhcp.log and so on) to the desired location:

(from the README)

-->Run Docker Container with mounted Zeek Volume:

```
docker run -p 8050:8050 -v {zeek_location}:/home/datascientist/zeek_input broai:latest
```

`zeek_location` is your folder where `conn.log` exists. I'm planning to create a docker-compose file that will create an experimental zeek logger for you. But for now you have to add your own logs.

**Comment by abdulghafor** [comment]
Thank you for your help . i came up with new issue as shown below .
![command](https://user-images.githubusercontent.com/71027093/105971798-be671480-60ac-11eb-8395-a8c46c0ad281.PNG)
![error 5](https://user-images.githubusercontent.com/71027093/105972836-d8edbd80-60ad-11eb-882d-dd252a501c16.PNG)

**Comment by herrfeder** [comment]
Yeah, thank you. Silly me did minor changes to the file path management stuff and tested it only in my Theia IDE and not with the Conainer Build again. I resolved it now with this commit https://github.com/herrfeder/AI_Cybersecurity_IDS_PoC/commit/2f8c919107b2499600561853c1399351d5273f50 . But after that I run into another error that only occurs in the Docker build but not in my IDE with the freshly cloned repo. Sometimes I hate computers xD. I will open another Issue for that. Thank you for testing. I really appreciate that.

**Comment by herrfeder** [comment]
Please see the other two issues. It should work now :)
and again thank you.
